vocabSet = [
    ["ἀγαθός", "good", "Chapter 7"],
    ["ἀνδρεῖος", "brave"],
    ["δεινός", "strange, terrible, clever"],
    ["ἐχθρός", "hostile"],
    ["ἰσχυρός", "strong"],
    ["κακός", "bad"],
    ["καλός", "beautiful, fine"],
    ["μακρός", "long"],
    ["σοφός", "wise"],
    ["φίλιος", "friendly"],
    ["χαλεπός", "difficult"],
    ["μικρός", "small", "Chapter 8"],
    ["ῥᾴδιος", "easy"],
    ["ἄξιος", "worthy", "Chapter 9"],
    ["αὐτός", "same"],
    ["ἄλλος", "other, another", "Chapter 16"],
    ["ἀρχαῖος", "ancient"],
    ["ἕκαστος", "each, every"],
    ["μέγας", "big, great, large"],
    ["πολύς", "much, many"],
    ["τάλας", "wretched"],
    ["δέκατος", "tenth", "Chapter 17"],
    ["πέμπτος", "fifth"]
]
