vocabSet = [
    ["ἀγορά", "market-place", "Chapter 3"],
    ["γέφυρα", "bridge"],
    ["δόξα", "glory"],
    ["ἐπιστολή", "letter"],
    ["ἡμέρα", "day"],
    ["θάλαττα", "sea"],
    ["θεά", "goddess"],
    ["κώμη", "village"],
    ["μάχη", "battle"],
    ["Μοῦσα", "Muse"],
    ["οἰκία", "house"],
    ["πύλη", "gate"],
    ["σοφία", "wisdom"],
    ["στρατιά", "army"],
    ["τιμή", "honor"],
    ["χώρα", "country"],
    ["Ἀθῆναι", "Athens", "Chapter 4"],
    ["Ἀθήνη", "Athena"],
    ["δικαιοσούνη", "justice"],
    ["εἰρήνη", "peace"],
    ["κριτής", "judge"],
    ["ναύτης", "sailor"],
    ["νεανίας", "young man"],
    ["Ξέρξης", "Xerxes"],
    ["Πέρσης", "Persian"],
    ["ποιητής", "poet"],
    ["πολίτης", "citizen"],
    ["Σπάρτη", "Sparta"],
    ["στρατιώτης", "soldier"],
    ["ταμίας", "steward"],
    ["Ἀθηναῖος", "Athenian", "Chapter 5"],
    ["δοῦλος", "slave"],
    ["ἰατρός", "doctor"],
    ["ἵππος", "horse"],
    ["λόγος", "word"],
    ["νῆσος", "island"],
    ["νόσος", "illness, plague"],
    ["ὁδός", "road, way, journey"],
    ["πόλεμος", "war"],
    ["ποταμός", "river"],
    ["στρατηγός", "general"],
    ["δένδρον", "tree", "Chapter 6"],
    ["δῶρον", "gift"],
    ["ἔργον", "work, deed"],
    ["ζυγόν", "yoke"],
    ["ζῷον", "animal"],
    ["καρπός", "fruit"],
    ["ὅπλα", "arms, weapons"],
    ["πολέμιοι", "enemy (group)"],
    ["σῖτος", "food"],
    ["στρατόπεδον", "(army) camp"],
    ["τέκνον", "child"],
    ["φιλία", "friendship"],
    ["ἄνθρωπος", "man (human being), person", "Chapter 7"],
    ["βάρβαρος", "foreigner (non-Greek)"],
    ["δεσπότης", "master (of a household)"],
    ["νίκη", "victory"],
    ["θώραξ", "breastplate", "Chapter 8"],
    ["κῆρυξ", "herald"],
    ["Λακεδαιμόνιος", "Spartan"],
    ["ὄνομα", "name"],
    ["σύμμαχος", "ally"],
    ["σῶμα", "body"],
    ["φύλαξ", "guard (a person)"],
    ["χρῆμα", "thing, (in pl.) money"],
    ["ἀσπίς", "shield", "Chapter 9"],
    ["Ἑλλάς", "Greece"],
    ["ἐλπίς", "hope, expectation"],
    ["κόρυς", "helmet"],
    ["λαμπάς", "torch"],
    ["ὄρνις", "bird"],
    ["παῖς", "child, boy, girl"],
    ["πατρίς", "fatherland, own country"],
    ["φυγάς", "exile (a person)"],
    ["χάρις", "grace, thanks"],
    ["Ἄλκηστις", "Alcestis", "Chapter 16"],
    ["ἔρως", "love, desire"],
    ["ἔτος", "year"],
    ["Ἡρακλῆς", "Heracles"],
    ["φόβος", "fear"],
    ["αἰχμάλωτος", "prisoner (of war)", "Chapter 17"],
    ["κεφαλή", "head"],
    ["μήν", "month"],
    ["νόμος", "law"],
    ["χρόνος", "time"]
]
