vocabSet = [
    ["ἄγω", "lead, bring", "Chapter 2"],
    ["γράφω", "write"],
    ["διώκω", "pursue"],
    ["ἔχω", "have"],
    ["θύω", "sacrifice"],
    ["κωλύω", "hinder, prevent"],
    ["λύω", "loose, set free"],
    ["πέμπω", "send"],
    ["φέρω", "carry, bear, bring"],
    ["φεύγω", "flee"],
    ["φυλάττω", "guard"],
    ["θεραπεύω", "honor, worship, heal, cure, tend", "Chapter 3"],
    ["παύω", "stop"],
    ["πείθω", "persuade"],
    ["στρατεύω", "march"],
    ["βασιλεύω", "be king, reign", "Chapter 4"],
    ["κωλύω (ἀπό)", "keep (someone) away (from)"],
    ["παιδεύω", "educate, teach, train"],
    ["πιστεύω", "trust, believe"],
    ["κινδυνεύω", "run risks", "Chapter 5"],
    ["μένω", "stay, remain, await, wait for"],
    ["βλάπτω", "harm, injure, damage", "Chapter 6"],
    ["ἐθέλω", "be willing, wish"],
    ["κελεύω", "order"],
    ["κόπτω", "cut, cut down"],
    ["παρέχω", "provide, cause, produce"],
    ["ἀγγέλλω", "announce, report", "Chapter 7"],
    ["εἰμί", "be"],
    ["λέγω", "say, speak, tell"],
    ["εὑρίσκω", "find, find out", "Chapter 8"],
    ["λαμβάνω", "take, capture, catch"],
    ["ὁπλίζω", "arm"],
    ["θαυμάζω", "wonder at, admire", "Chapter 9"],
    ["οἷός τέ εἰμι", "be able, can"],
    ["χάριν ἔχω", "be grateful"],
    ["ἀποθνῄσκω", "die", "Chapter 10"],
    ["ἀποκτείνω", "kill"],
    ["σῴζω", "save, protect"],
    ["ἀκούω", "hear, listen to", "Chapter 11"],
    ["ἀναγκάζω", "force, compel"],
    ["ἀποφεύγω", "flee away, escape"],
    ["ἄρχω", "rule, command"],
    ["εἰσβάλλω", "throw into, invade, flow into"],
    ["ἥκω", "have come"],
    ["καταλύω", "destroy"],
    ["πράττω", "do, manage; fare"],
    ["προπέμπω", "send forth"],
    ["συμβουλεύω", "advise"],
    ["ταράττω", "throw into confusion"],
    ["τάττω", "draw up"],
    ["ἄπειμι", "be absent", "Chapter 12"],
    ["εὖ πράττω", "fare well, manage well"],
    ["κακῶς πράττω", "fare badly"],
    ["πίπτω", "fall"],
    ["ἀπάγω", "lead away, bring back", "Chapter 13"],
    ["ἐλπίζω", "hope, expect"],
    ["μέλλω", "be about to, intend"],
    ["παρασκευάζω", "prepare"],
    ["καταλείπω", "leave behind", "Chapter 14"],
    ["κρύπτω", "hide"],
    ["λείπω", "leave"],
    ["νομίζω", "think"],
    ["τύπτω", "strike, hit"],
    ["φημί", "say"],
    ["οὔ φημι", "say...not, deny"],
    ["ἀπελαύνω", "drive away, march away", "Chapter 15"],
    ["ἐλαύνω", "drive, march"],
    ["σπεύδω", "hasten, hurry", "Chapter 16"],
    ["δέχομαι", "receive", "Chapter 17"],
    ["λύομαι", "ransom"],
    ["μάχομαι", "fight"],
    ["μιμνήσκω", "remind"],
    ["μιμνήσκομαι", "remember, mention"],
    ["ὀνομάζω", "name, call (by name)"],
    ["παύομαι", "cease from"],
    ["πείθομαι", "obey"],
    ["πορεύω", "carry, convey"],
    ["πορεύoμαι", "march, journey"]
]
